### ISSUE TITLE
Update gcloud docs to show login

### ISSUE THREAD

**Issue by buranch-mike** [outlier-org/onboarding#2]
Currently, on the docs that show how to set up `gcloud` on readme there missing a piece of information about setting the Application Default Credentials on CLI

**Comment by tchaffee** [comment]
From Slack (https://outlierslack.slack.com/archives/CKTKQ43RD/p1562360642065800):

> Can you add a PR to add to the readme to explain how to get the gcloud CLI set up
> https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login
> you are now a storage object admin for the outlier-dev project
> the bucket is also outlier-dev
> so once you have the gcloud CLI set up you should be good

**Comment by tchaffee** [comment]
@buranch-mike was this already fixed by https://github.com/outlier-org/outlier-api/pull/8 ? Or is this in addition to #8?

**Comment by buranch-mike** [comment]
@tchaffee sorry this has been already fixed and merged on `outlier-api` repo. It was an unfortunate mistake I creating the PR here.
